env:
  browser: true
  node: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - never
  no-var:
    -0
